Import('builder')

builder.SConscript('statics/SConscript')

builder.Library('statics', 'statics.cc', libs = ['@ordered-function-registry',])

builder.Library('output-handler',
        ['output-handler.cc'],
        libs = ['#boost_thread',])

builder.Library('timer', 'timer.cc', libs = ['rt',])
builder.AddBoostTest('timer_test.cc', libs=['@timer'])

builder.Library('logging', 'logging.cc',
        libs = ['@output-handler', '@statics', ])
builder.AddBoostTest('logging_test.cc', libs = ['@logging',])

builder.Library('string-algo', 'string-algo.cc', libs = ['@logging',])
builder.AddBoostTest('string-algo_test.cc', libs = ['@string-algo',])

builder.Library('util', 'util.cc', libs = ['@logging', '@string-algo'])
builder.AddBoostTest('util_test.cc', libs = ['@util'])

# The following are testing things that are only in .h files so there's no
# corresponding library to link.
builder.AddBoostTest('check_test.cc',
        libs = ['boost_regex', '@logging', '@string-algo'])
builder.AddBoostTest('topological-iterator_test.cc', libs = [])
